### ISSUE TITLE
recut Halloween Sudoku image for chrome store

### ISSUE THREAD

**Issue by Battagline** [Battagline/247GamesTEST2#19]
<img width="159" alt="screen shot 2015-10-01 at 1 29 06 pm" src="https://cloud.githubusercontent.com/assets/556292/10229969/68101bc8-6840-11e5-878f-6a136edaf9ae.png">

^^ it looks "squished"

**Comment by mikeslow** [comment]
![440x280_halloween_sudoku](https://cloud.githubusercontent.com/assets/14874132/10231395/b5698284-683f-11e5-8826-1554565d0eb0.png)
![920x680_halloween_sudoku](https://cloud.githubusercontent.com/assets/14874132/10231394/b56761ca-683f-11e5-9be2-75761037e3cd.png)
![1400x560_halloween_sudoku](https://cloud.githubusercontent.com/assets/14874132/10231396/b569a278-683f-11e5-82d2-4a0034343f7d.png)

**Comment by dejaemoore** [comment]
changed and updated.
