### ISSUE TITLE
create seasonal blackjack sites

### ISSUE THREAD

**Issue by Battagline** [Battagline/247GamesTEST2#2]

**Comment by dejaemoore** [comment]
summer complete, Fall in motion

**Comment by Battagline** [comment]
great!

**Comment by dejaemoore** [comment]
Fall complete
![image](https://cloud.githubusercontent.com/assets/14873837/10147061/74ee7ffc-65f1-11e5-956c-5fdc82e2ef83.png)

**Comment by dejaemoore** [comment]
Halloween done.
www.halloweenblackjack.com
![image](https://cloud.githubusercontent.com/assets/14873837/10319226/d0241840-6c32-11e5-9ecf-9640ead16c3c.png)

**Comment by dejaemoore** [comment]
Thanksgiving done.
http://www.thanksgivingblackjack.com/

![image](https://cloud.githubusercontent.com/assets/14873837/10945045/b221f1bc-82e1-11e5-929b-f18285cbabc7.png)

**Comment by dejaemoore** [comment]
www.christmasblackjack.com
![image](https://cloud.githubusercontent.com/assets/14873837/11077406/97e554ae-87c5-11e5-8fab-0557a40a2c0d.png)

**Comment by dejaemoore** [comment]
www.winterblackjack.com

![image](https://cloud.githubusercontent.com/assets/14873837/12180139/6e1c9a94-b540-11e5-854f-34611e6b5f3a.png)

**Comment by dejaemoore** [comment]
www.valentineblackjack.com
![image](https://cloud.githubusercontent.com/assets/14873837/12857003/5eb3d930-cc0d-11e5-9503-5fb4bf347e82.png)
