### ISSUE TITLE
finish 247checkers website

### ISSUE THREAD

**Issue by Battagline** [Battagline/247GamesTEST2#33]
plugins
google ads
text content
external links
etc.

**Comment by dejaemoore** [comment]
www.247checkers.com
![image](https://cloud.githubusercontent.com/assets/14873837/11044217/385d5e58-86e6-11e5-87ef-9980f8c9db16.png)

**Comment by dejaemoore** [comment]
Let's talk to Geoff about finishing this site - add glows for turn taking, chip counters, etc
