### ISSUE TITLE
create list of assets to be changed per Checkers reskin

### ISSUE THREAD

**Issue by Battagline** [Battagline/247GamesTEST2#35]
- given 247checkers template, create list of image files tobe changed for seasonal reskins / NOTE: some of the file extensions have changed ("Checkers-SVG-Board.svg" is now "Checkers-SVG-Board.jpg")
- change filenames to use consistent spacing schema (choose " " or "-" or "_")
- remove "SVG" from all file names
- create list of all files changed, and to what: ("Checkers-SVG_Red Checker Button.svg" -> "Checkers-Red-Checker-Button.svg")

**Comment by mikeslow** [comment]
**Reskin Items:**

Checkers-SVG-Counter.svg > checkers-counter.svg

favicon.ico > favicon.ico
Game-title.png > checkers-title-web.png

Checkers-SVG-Title-Icon.png > checkers-title-intro.png

Checkers-SVG-Board.jpg > checkers-board.jpg
Game-texture1.png > checkers-texture-web.png
Game-texture2.png > checkers-texture-game.png

Checkers-SVG-Black-Checker-Button.svg > checkers-button-checker-black.svg
Checkers-SVG-Black-Checker-King.svg > checkers-checker-black-king.svg
Checkers-SVG-Black-Checker.svg > checkers-checker-black.svg

Checkers-SVG-Red-Checker-Button.svg > checkers-button-checker-red.svg
Checkers-SVG-Red-Checker-King.svg > checkers-checker-red-king.svg
Checkers-SVG-Red-Checker.svg > checkers-checker-red.svg

**Global Items:**

Checkers-SVG-Award.svg > checkers-award.svg

Checkers-SVG-Games.svg > checkers-button-more-games.svg
Checkers-SVG-Resume.svg > checkers-button-resume.svg
Checkers-SVG-Start.svg > checkers-button-start.svg
Checkers-SVG-New-Game.svg > checkers-button-new-game.svg
Checkers-SVG-Replays.svg > checkers-button-replay.svg

Checkers-SVG-1-Player.svg > checkers-button-1-player.svg
Checkers-SVG-2-Player.svg > checkers-button-2-player.svg

Home-Button_Home.svg > checkers-button-home.svg
Checkers-SVG-Hint.svg > checkers-button-hint.svg
Checkers-SVG-Sound-On.svg > checkers-button-sound-on.svg
Checkers-SVG-Sound-Off.svg > checkers-button-sound-off.svg
Checkers-SVG-Select.svg > checkers-button-select.svg
Checkers-SVG-Go-Back.svg > checkers-button-go-back.svg
Checkers-SVG-Rate-Us.svg > checkers-button-rate-us.svg

Checkers-SVG-Off-Switch.svg > checkers-button-off-switch.svg
Checkers-SVG-On-Switch.svg > checkers-button-on-switch.svg

Checkers-SVG-Easy.svg > checkers-button-difficulty-easy.svg
Checkers-SVG-Medium.svg > checkers-button-difficulty-medium.svg
Checkers-SVG-Hard.svg > checkers-button-difficulty-hard.svg

Checkers-SVG_Green Highlight.svg > checkers-highlight-green.svg
Checkers-SVG-White-Highlight.svg > checkers-highlight-white.svg
Checkers-SVG-Yellow-Highlight.svg > checkers-highlight-yellow.svg
Checkers-SVG-Red-Highlight.svg > checkers-highlight-red.svg

Checkers-SVG-Menu-BG.svg > checkers-menu-bg.svg
GAME-bottom-highlight.png > checkers-web-highlight-bottom.png
GAME-header-bg.png > checkers-web-header-bg.png
