### ISSUE TITLE
github test: CLOSE ME OUT, MIKE

### ISSUE THREAD

**Issue by Battagline** [Battagline/247GamesTEST2#6]
My little pony died :(

**Comment by mikeslow** [comment]
Dumptrucks are neato.

**Comment by Battagline** [comment]
lemme smell yo dick

<img width="804" alt="beach4" src="https://cloud.githubusercontent.com/assets/556292/10138552/a98448b4-65c4-11e5-84d4-7219f213bac2.png">

**Comment by mikeslow** [comment]
![graphics-247-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10138584/7500550e-65bc-11e5-8cbf-17004665e761.png)
