### ISSUE TITLE
Create skins: Roulette

### ISSUE THREAD

**Issue by Battagline** [Battagline/247GamesTEST2#7]

**Comment by mikeslow** [comment]
![graphics-winter-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10138811/6374d71e-65bd-11e5-9ac5-06a3de3b70be.png)

**Comment by mikeslow** [comment]
Winter Roulette Mockups:
![graphics-winter-roulette-8](https://cloud.githubusercontent.com/assets/14874132/10150921/daa3760a-65ff-11e5-8582-ea394249684b.png)
![graphics-winter-roulette-7](https://cloud.githubusercontent.com/assets/14874132/10150926/daa4ede6-65ff-11e5-8222-bdbb531900a5.png)
![graphics-winter-roulette-6](https://cloud.githubusercontent.com/assets/14874132/10150924/daa45fa2-65ff-11e5-8a47-6709b01d2920.png)
![graphics-winter-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10150923/daa45e1c-65ff-11e5-8853-abefffd725a3.png)
![graphics-winter-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10150925/daa4b1dc-65ff-11e5-9d77-515dda7b88b8.png)
![graphics-winter-roulette-3](https://cloud.githubusercontent.com/assets/14874132/10150922/daa3bd40-65ff-11e5-8bbe-2a7a272f9a91.png)
![graphics-winter-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10150927/dab40678-65ff-11e5-8798-43badb918f38.png)
![graphics-winter-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10150928/dab52332-65ff-11e5-9103-bb43946598a8.png)

**Comment by mikeslow** [comment]
Roulette Skin Update:
• 247Roulette: All assets completed and added to gD (title, icon, bg tiles, fonts, ai, fla , etc)
• WinterRoulette: Roulette Wheel updated with 'Snowflakes'
• WinterRoulette: Promos for approval 'in progress'

**Comment by mikeslow** [comment]
![graphics-winter-roulette-8](https://cloud.githubusercontent.com/assets/14874132/10292251/792eba4e-6b6b-11e5-8380-6f5b017427bf.png)
![graphics-winter-roulette-7](https://cloud.githubusercontent.com/assets/14874132/10292248/792bea3a-6b6b-11e5-8d69-be597197748e.png)
![graphics-winter-roulette-6](https://cloud.githubusercontent.com/assets/14874132/10292249/792c856c-6b6b-11e5-801a-56bcb8aab556.png)
![graphics-winter-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10292253/793123ec-6b6b-11e5-85a6-879ede2292a2.png)
![graphics-winter-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10292250/792d0528-6b6b-11e5-9cac-9a13c9e2b9ec.png)
![graphics-winter-roulette-3](https://cloud.githubusercontent.com/assets/14874132/10292252/792f0936-6b6b-11e5-8009-1ced11c2323c.png)
![graphics-winter-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10292254/7938cc50-6b6b-11e5-9076-b8586dd309ab.png)
![graphics-winter-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10292255/793ca938-6b6b-11e5-9394-99564508ad9b.png)

**Comment by mikeslow** [comment]
![graphics-christmas-roulette-8](https://cloud.githubusercontent.com/assets/14874132/10292266/891d42fe-6b6b-11e5-929a-453c9fbbf92b.png)
![graphics-christmas-roulette-7](https://cloud.githubusercontent.com/assets/14874132/10292269/892e3c26-6b6b-11e5-8ebf-483abbce2796.png)
![graphics-christmas-roulette-6](https://cloud.githubusercontent.com/assets/14874132/10292267/892db38c-6b6b-11e5-89f6-1deda5a2b940.png)
![graphics-christmas-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10292268/892dd3c6-6b6b-11e5-9dda-86e647c9eaa4.png)
![graphics-christmas-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10292272/893260a8-6b6b-11e5-83e7-f921ba834912.png)
![graphics-christmas-roulette-3](https://cloud.githubusercontent.com/assets/14874132/10292271/8930a894-6b6b-11e5-9a98-754171d47834.png)
![graphics-christmas-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10292270/892e83ca-6b6b-11e5-9ef0-96cb874b9673.png)
![graphics-christmas-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10292273/893cc00c-6b6b-11e5-873d-162e8e21e6b1.png)

**Comment by mikeslow** [comment]
![graphics-stpatricksday-roulette-8](https://cloud.githubusercontent.com/assets/14874132/10292286/9cd0a43a-6b6b-11e5-9040-2c24c01e7c83.png)
![graphics-stpatricksday-roulette-7](https://cloud.githubusercontent.com/assets/14874132/10292285/9ccf5936-6b6b-11e5-9f78-93ac6fea41a6.png)
![graphics-stpatricksday-roulette-6](https://cloud.githubusercontent.com/assets/14874132/10292284/9cceeca8-6b6b-11e5-9731-4d28c67aaabe.png)
![graphics-stpatricksday-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10292287/9cd123ec-6b6b-11e5-972a-30e4812a029b.png)
![graphics-stpatricksday-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10292288/9cd1ffc4-6b6b-11e5-9805-4bced5c4393d.png)
![graphics-stpatricksday-roulette-3](https://cloud.githubusercontent.com/assets/14874132/10292289/9cd8388a-6b6b-11e5-9fb7-61eab82865ac.png)
![graphics-stpatricksday-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10292290/9cdc40d8-6b6b-11e5-9cab-e1b0b3470fca.png)
![graphics-stpatricksday-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10292291/9cdf4526-6b6b-11e5-9b70-01df587a15a1.png)

**Comment by mikeslow** [comment]
![graphics-stpatricksday-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10489502/a0499edc-725a-11e5-8e11-ee6ef785508c.png)
![graphics-stpatricksday-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10489499/a0476162-725a-11e5-951d-fdbb94e99da9.png)
![Uploading graphics-stpatricksday-roulette-3.png…]()
![graphics-stpatricksday-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10489501/a047b89c-725a-11e5-87fb-54ea25a8f0bc.png)
![graphics-stpatricksday-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10489498/a0474c72-725a-11e5-833d-5c802afaf4ef.png)
![graphics-stpatricksday-roulette-6](https://cloud.githubusercontent.com/assets/14874132/10489500/a04767f2-725a-11e5-8fb7-236d8dc70cbd.png)
![Uploading graphics-stpatricksday-roulette-7.png…]()
![Uploading graphics-stpatricksday-roulette-8.png…]()

**Comment by mikeslow** [comment]
![graphics-4thofjuly-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10489519/b8624b4a-725a-11e5-8919-4cd6ed13fbf6.png)
![graphics-4thofjuly-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10489520/b8629cee-725a-11e5-9576-34ccbc3612d8.png)
![Uploading graphics-4thofJuly-roulette-3.png…]()
![graphics-4thofjuly-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10489522/b865c950-725a-11e5-90dd-bc444cde1190.png)
![graphics-4thofjuly-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10489521/b8641fce-725a-11e5-848e-40eb8d2fb59b.png)
![Uploading graphics-4thofJuly-roulette-6.png…]()
![Uploading graphics-4thofJuly-roulette-7.png…]()
![Uploading graphics-4thofJuly-roulette-8.png…]()

**Comment by mikeslow** [comment]
![graphics-fall-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10489543/c461d014-725a-11e5-843c-8584c71bdd17.png)
![graphics-fall-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10489546/c4642418-725a-11e5-8f29-d14c5f7f43e9.png)
![Uploading graphics-fall-roulette-3.png…]()
![Uploading graphics-fall-roulette-4.png…]()
![graphics-fall-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10489544/c4631b2c-725a-11e5-8ace-3aa9cd11fdef.png)
![graphics-fall-roulette-6](https://cloud.githubusercontent.com/assets/14874132/10489542/c460b27e-725a-11e5-8b9b-15a99ca371d3.png)
![Uploading graphics-fall-roulette-7.png…]()
![Uploading graphics-fall-roulette-8.png…]()

**Comment by mikeslow** [comment]
![graphics-stpatricksday-roulette-8](https://cloud.githubusercontent.com/assets/14874132/10489594/f2306e10-725a-11e5-9f28-eaa0141f7e3c.png)
![graphics-stpatricksday-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10489599/f234661e-725a-11e5-823c-c076719cf6eb.png)
![graphics-stpatricksday-roulette-3](https://cloud.githubusercontent.com/assets/14874132/10489597/f2321b16-725a-11e5-8be7-4042d578e54e.png)
![graphics-stpatricksday-roulette-7](https://cloud.githubusercontent.com/assets/14874132/10489598/f2324e1a-725a-11e5-8c63-21fd6758a037.png)
![graphics-stpatricksday-roulette-6](https://cloud.githubusercontent.com/assets/14874132/10489596/f231fbea-725a-11e5-834c-6ba6c80ad247.png)
![graphics-stpatricksday-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10489595/f231ef74-725a-11e5-9499-01e9292784e4.png)
![graphics-stpatricksday-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10489601/f2417296-725a-11e5-9c8f-3672a19c19a8.png)
![graphics-stpatricksday-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10489600/f23ef8ea-725a-11e5-827a-7c7441942b2d.png)

**Comment by mikeslow** [comment]
![graphics-4thofjuly-roulette-8](https://cloud.githubusercontent.com/assets/14874132/10489626/0392944e-725b-11e5-9f43-a35d379c8558.png)
![graphics-4thofjuly-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10489621/038e880e-725b-11e5-9591-c4bc7f98e2e8.png)
![graphics-4thofjuly-roulette-3](https://cloud.githubusercontent.com/assets/14874132/10489622/038f3aa6-725b-11e5-92d9-cd040cb6ec09.png)
![graphics-4thofjuly-roulette-7](https://cloud.githubusercontent.com/assets/14874132/10489623/038f6904-725b-11e5-8273-6b452c88a940.png)
![graphics-4thofjuly-roulette-6](https://cloud.githubusercontent.com/assets/14874132/10489624/03903514-725b-11e5-999c-74034159c1e9.png)
![graphics-4thofjuly-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10489625/03904fa4-725b-11e5-9ef8-7c34525a9baa.png)
![graphics-4thofjuly-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10489627/039ab246-725b-11e5-8f6c-699e6a61f3db.png)
![graphics-4thofjuly-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10489628/039ecca0-725b-11e5-99db-d37d9aa0e343.png)

**Comment by mikeslow** [comment]
![graphics-fall-roulette-1](https://cloud.githubusercontent.com/assets/14874132/10489643/163ce4be-725b-11e5-93b3-85065993c2d4.png)
![graphics-fall-roulette-8](https://cloud.githubusercontent.com/assets/14874132/10489644/16552678-725b-11e5-84fd-adc54379f8df.png)
![graphics-fall-roulette-7](https://cloud.githubusercontent.com/assets/14874132/10489648/165c8b34-725b-11e5-9618-a9595ec9a1ea.png)
![graphics-fall-roulette-6](https://cloud.githubusercontent.com/assets/14874132/10489645/165a9c0c-725b-11e5-8522-850056aac17f.png)
![graphics-fall-roulette-5](https://cloud.githubusercontent.com/assets/14874132/10489646/165b3b1c-725b-11e5-9ee7-dd71362e1c16.png)
![graphics-fall-roulette-4](https://cloud.githubusercontent.com/assets/14874132/10489649/165e7642-725b-11e5-8adf-d2f8d0ac871b.png)
![graphics-fall-roulette-3](https://cloud.githubusercontent.com/assets/14874132/10489647/165b5188-725b-11e5-8439-6c82cda01f5f.png)
![graphics-fall-roulette-2](https://cloud.githubusercontent.com/assets/14874132/10489650/1666da9e-725b-11e5-8448-213f1f57dca0.png)

**Comment by mikeslow** [comment]
**Skins Finished**

**Promos Finished**

**Titles + Icons to Finished**
