### ISSUE TITLE
Slots Promos

### ISSUE THREAD

**Issue by dejaemoore** [Battagline/247GamesTEST2#86]
After mockups are finished, create and cut promotional images for all seasonal variations. Add to GD.

**Comment by mikeslow** [comment]
### **Slots Promos Checklist:**

---

• _Fall (7/13/16)_
• _Summer (7/12/16)_
• _4th of July (7/12/16)_
• _St Patty's Day (7/12/16)_
• _Spring (7/12/16)_
• _Cinco De Mayo (7/11/16)_
• _247 (7/8/16)_
• _Easter (7/8/16)_
• _Valentines Day (7/8/16)_
• _Christmas (7/7/16)_
• _Winter (7/7/16)_
• _Halloween (6/27/16)_
• _Thanksgiving (6/27/16)_
• _New Year's (6/23/16)_
